name: db-ticketplay
services:

  db:
    image: postgres:16-alpine3.20
    env_file:
      - .env
    container_name: postgres-tickets
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ticketsdb
    volumes:
      - ./postgresql:/var/lib/postgresql/data
