###
GET http://localhost:8080/reporte/vendidos/total HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/reporte/vendidos/cancha HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/reporte/vendidos/tribuna HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/reporte/vendidos/general HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/reporte/ganancias HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/reporte/abonados HTTP/1.1
content-type: application/json